### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by hujiba** [tehmantra/proofing_box#3]
Hi again,
I know this is my third issue post here, so I hope I don’t have to delete this one immediately as well, when i figure out the problem.
On startup when I’m running the code, the display does not show anything. I’m using the exact one you used, and it’s wired like the diagram. When I run the test from circuit.io, it works perfectly and displays correctly, so I think the pins are correct and the display is working. However, nothing shows no matter what I do when I run the proofing box code. Thanks!

**Comment by m-wild** [comment]
Sorry, I just realized that in the code, I have connected to different pins than in the diagram.

I have just updated the code on github to match the wiring diagram from circuit.io 
I have also added wiring instructions recently which I have updated too.

Just uploaded this code to my proofing box and it is working :)

Let me know if you have any more problems.
